#cloud-config
# Add groups to the system
# The following example adds the ubuntu group with members 'root' and 'sys'
# and the empty group cloud-users.
groups:
  - ubuntu: [root,sys]
  - cloud-users

# Add users to the system. Users are added after groups are added.
# Note: Most of these configuration options will not be honored if the user
#       already exists. Following options are the exceptions and they are
#       applicable on already-existing users:
#       - 'plain_text_passwd', 'hashed_passwd', 'lock_passwd', 'sudo',
#         'ssh_authorized_keys', 'ssh_redirect_user'.
users:
  - default
  - name: gmu
    gecos: John L Olsen
    primary_group: gmu
    groups: users, admin
    selinux_user: staff_u
    expiredate: '2032-09-01'
    ssh_import_id: gmu
    plain_text_passwd: true
    lock_passwd: false
    passwd: gmu
  - name: ubuntu
    gecos: John L Olsen
    groups: users, admin
    ssh_import_id: None
    plain_text_passwd: true
    lock_passwd: false

