version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /home/ubuntu/registry
http:
  addr: 10.80.202.79:5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: basic-realm
    path: /home/ubuntu/.htpasswd
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
