create role cheirrs_user with login password 'passwd';
create role cheirrs_admin with superuser login password 'passwd';
create role cheirrs_oseer_admin with superuser login password 'passwd';
create role a_horse_admin with superuser login password 'passwd';
create role chubba_morris_user with login password 'passwd';
create role chubba_morris_admin with superuser login password 'passwd';
create role chubba_morris_oseer_admin with superuser login password 'passwd';
create role convey_it_user with login password 'passwd';
create role convey_it_admin with superuser login password 'passwd';
create role convey_it_oseer_admin with superuser login password 'passwd';
create role the_general_user with login password 'passwd';
create role the_general_admin with superuser login password 'passwd';
create role the_general_oseer_admin with superuser login password 'passwd';
create role gmu with login password 'gmu';
