---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-web
  template:
    metadata:
      labels:
        app: smart-web
    spec:
      containers:
      - name: smart-web
        image: registry.gitlab.com/john_olsenjohn-itcsolutions/smart:1
        ports:
        - containerPort: 8001

